package themes

import "github.com/alecthomas/chroma/v2"

func init() {
	register("cursor-dark", chroma.StyleEntries{
		chroma.Background:          "bg:#181818 #D1D1D1",
		chroma.CodeLine:            "#D1D1D1",
		chroma.Error:               "#F14C4C",
		chroma.LineHighlight:       "bg:#262626",
		chroma.LineNumbers:         "#808080",
		chroma.LineNumbersTable:    "#808080",

		chroma.Keyword:             "#82D2CE",
		chroma.KeywordConstant:     "#82D2CE",
		chroma.KeywordDeclaration:  "#82D2CE",
		chroma.KeywordNamespace:    "#82D2CE italic",
		chroma.KeywordPseudo:       "#82D2CE",
		chroma.KeywordReserved:     "#82D2CE",
		chroma.KeywordType:         "#87C3FF",

		chroma.Name:                "#D1D1D1",
		chroma.NameAttribute:       "#AAA0FA",
		chroma.NameBuiltin:         "#9CDCFE",
		chroma.NameBuiltinPseudo:   "#CC7C8A italic",
		chroma.NameClass:           "#EFB080 bold",
		chroma.NameConstant:        "#F8C762",
		chroma.NameDecorator:       "#A8CC7C bold",
		chroma.NameEntity:          "#88C0D0",
		chroma.NameException:       "#FC6B83",
		chroma.NameFunction:        "#EBC88D",
		chroma.NameFunctionMagic:   "#EBC88D",
		chroma.NameLabel:           "#82D2CE",
		chroma.NameNamespace:       "#D1D1D1",
		chroma.NameOther:           "#D1D1D1",
		chroma.NameProperty:        "#AAA0FA",
		chroma.NameTag:             "#87C3FF",
		chroma.NameVariable:        "#9CDCFE",
		chroma.NameVariableClass:   "#9CDCFE",
		chroma.NameVariableGlobal:  "#9CDCFE",
		chroma.NameVariableInstance: "#9CDCFE",
		chroma.NameVariableMagic:   "#9CDCFE",

		chroma.Literal:             "#D1D1D1",
		chroma.LiteralDate:         "#D1D1D1",
		chroma.LiteralString:       "#E394DC",
		chroma.LiteralStringAffix:  "#82D2CE",
		chroma.LiteralStringBacktick: "#E394DC",
		chroma.LiteralStringChar:   "#E394DC",
		chroma.LiteralStringDelimiter: "#E394DC",
		chroma.LiteralStringDoc:    "#808080 italic",
		chroma.LiteralStringDouble: "#E394DC",
		chroma.LiteralStringEscape: "#F8C762",
		chroma.LiteralStringHeredoc: "#808080",
		chroma.LiteralStringInterpol: "#E394DC",
		chroma.LiteralStringOther:  "#E394DC",
		chroma.LiteralStringRegex:  "#F8C762",
		chroma.LiteralStringSingle: "#E394DC",
		chroma.LiteralStringSymbol: "#E394DC",
		chroma.LiteralNumber:       "#EBC88D",
		chroma.LiteralNumberBin:    "#EBC88D",
		chroma.LiteralNumberFloat:  "#EBC88D",
		chroma.LiteralNumberHex:    "#EBC88D",
		chroma.LiteralNumberInteger: "#EBC88D",
		chroma.LiteralNumberIntegerLong: "#EBC88D",
		chroma.LiteralNumberOct:    "#EBC88D",

		chroma.Operator:            "#D1D1D1",
		chroma.OperatorWord:        "#82D2CE",

		chroma.Comment:             "italic #808080",
		chroma.CommentHashbang:     "italic #808080",
		chroma.CommentMultiline:    "italic #808080",
		chroma.CommentPreproc:      "italic #A8CC7C",
		chroma.CommentPreprocFile:  "bold #A8CC7C",
		chroma.CommentSingle:       "italic #808080",
		chroma.CommentSpecial:      "italic #808080",

		chroma.Generic:             "#D1D1D1",
		chroma.GenericDeleted:      "#FC6B83 bg:#181818",
		chroma.GenericEmph:         "italic #D1D1D1",
		chroma.GenericError:        "#F14C4C",
		chroma.GenericHeading:      "bold #EBC88D",
		chroma.GenericInserted:     "bg:#181818 #70B489",
		chroma.GenericOutput:       "#D1D1D1",
		chroma.GenericPrompt:       "#D1D1D1",
		chroma.GenericStrong:       "bold #D1D1D1",
		chroma.GenericSubheading:   "bold #EBC88D",
		chroma.GenericTraceback:    "#F14C4C",
		chroma.GenericUnderline:    "underline #D1D1D1",
	})
}
